version: "3"
services:
  frontend:
    build: .
    command: npm run serve
    env_file:
      - ./env/dev.env
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
      - ./public:/app/public
      - ./src:/app/src
